### ISSUE TITLE
FATAL: failed to acquire the FSM lock in libgrypt: Invalid argument

### ISSUE THREAD

**Issue by r-arias** [johnschug/rust-gcrypt#1]
Hi,
thanks for creating this wrapper. I am new to rust and I am trying to build and test a library for mobile. I just got a 

```
FATAL: failed to acquire the FSM lock in libgrypt: Invalid argument
```

and cannot reproduce it very deterministically. It seems to happen sometimes and sometimes not. Any hints on where I should start looking? If you need more information to answer that, let me know!
Right now, all I am using within my code is `SExpression::from_str()` and `SExpression::from_bytes()` as well as `SExpression::to_bytes(Format::Advanced)`. Is there anything I should be more careful about when using these functions? 

Thanks in advance! 
EDIT: I also use `SExpression::generate_key()` from the `pkey` module...

**Comment by johnschug** [comment]
Hello, it sounds like the library has not been fully initialized. The library must be initialized using the [result](https://johnschug.github.io/rust-gcrypt/gcrypt/struct.Initializer.html) from [gcrypt::init](https://johnschug.github.io/rust-gcrypt/gcrypt/fn.init.html) before calling any other function in the library. You can find more information on the various options for initialization in the [libgcrypt documentation](https://www.gnupg.org/documentation/manuals/gcrypt/Initializing-the-library.html#Initializing-the-library). You can also see an example of initialization using the wrapper in [the setup function](https://github.com/johnschug/rust-gcrypt/blob/master/tests/basic.rs#L17) in tests/basic.rs. The token that is used as the Err result of gcrypt::init is used by most functions (see [Cipher::new](https://johnschug.github.io/rust-gcrypt/gcrypt/cipher/struct.Cipher.html)) in the wrapper to ensure initialization has occurred, but I haven't got around to adding it to the sexp and pkey modules yet.

EDIT: I just published a new version of the crate that should improve initialization and catch this
during compilation. See the [documentation](https://johnschug.github.io/rust-gcrypt/) for the tweaked initialization process.

**Comment by r-arias** [comment]
Ah well, thanks a lot for the answer!
Good to know I was being an idiot and nothing is actually broken :)
Thanks for your work, I'll close this issue and see what happens if I do it the way I am supposed to...
