### ISSUE TITLE
Why were versions >0.4.0 yanked?

### ISSUE THREAD

**Issue by theli-ua** [johnschug/rust-gcrypt#5]
I couldn't find info anywhere

**Comment by johnschug** [comment]
To be honest, I didn't expect anyone to notice. The versions after 0.4.0 included bundled versions of the upstream libgcrypt library, which have various security vulnerabilities. They were yanked to comply with community guidelines on crates with known security vulnerabilities.

**Comment by theli-ua** [comment]
I see. thanks for the explanation.

**Comment by theli-ua** [comment]
Actually, one more question - do you plan to release an updated version?
